version: 2.1

jobs:
  build:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apt update && apt install -y --no-install-recommends \
            wget \
            && rm -rf /var/lib/apt/lists/*
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/shinyproxy.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/shinyproxy.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=shinyproxy -t shinyproxy .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/shinyproxy.tar shinyproxy
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/shinyproxy.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag shinyproxy tetherlessworld/hadatac-shinyproxy
              docker push tetherlessworld/hadatac-shinyproxy
            fi